### ISSUE TITLE
Sometimes after cron / check for updates a corrupt zip is stored on the server

### ISSUE THREAD

**Issue by khartahk** [froger-me/wp-packages-update-server#11]
Sometimes when an automatic plugin / theme update is triggered a corrupt zip is stored on the server. When I the visit the overview page I get an empty page. This is the error I get when visiting the Overview page:
```
[Tue Feb 19 21:16:53.226198 2019] [php7:error] [pid 26188] [client www.xxx.yyy.zzz:32844] PHP Fatal error: Uncaught Wpup_InvalidPackageException: The specified file /nas/content/live/wpkupisi/wp-content/wppus/packages/bohinj-si-stage.zip does not contain a valid WordPress plugin or theme. in /nas/content/live/wpkupisi/wp-content/plugins/wp-plugin-update-server/lib/wp-update-server/includes/Wpup/ZipMetadataParser.php:128\nStack trace:\n#0 /nas/content/live/wpkupisi/wp-content/plugins/wp-plugin-update-server/lib/wp-update-server/includes/Wpup/ZipMetadataParser.php(102): Wpup_ZipMetadataParser->extractMetadata()\n#1 /nas/content/live/wpkupisi/wp-content/plugins/wp-plugin-update-server/lib/wp-update-server/includes/Wpup/ZipMetadataParser.php(74): Wpup_ZipMetadataParser->setMetadata()\n#2 /nas/content/live/wpkupisi/wp-content/plugins/wp-plugin-update-server/lib/wp-update-server/includes/Wpup/Package.php(67): Wpup_ZipMetadataParser->__construct(NULL, '/nas/content/li...', Object(Wpup_FileCache))\n#3 /nas/content/live/wpkupisi/wp-content/plugins/wp-plugin-update-server/inc/class-wppus-update-manager.php(785): Wpup_Package::fr in /nas/content/live/wpkupisi/wp-content/plugins/wp-plugin-update-server/lib/wp-update-server/includes/Wpup/ZipMetadataParser.php on line 128, referer: https://DOMAIN.TLD/wp-admin/admin.php?page=wppus-page-remote-sources
```

Can you set a try catch for this case and display which theme / plugin is corrupt? What exactly is the issue that this happens I haven't seen anything in the log yet but it doesn't happen when I update manually.

**Comment by froger-me** [comment]
Fixed in dev branch (2.0)
